import { async, TestBed } from '@angular/core/testing';

import { HttpClientService } from './http-client.service';
import { HttpClient, HttpHandler, HttpClientModule } from '@angular/common/http';
import {HttpClientTestingModule, HttpTestingController} from "@angular/common/http/testing";

describe('HttpClientService', () => {
  let service: HttpClientService;
  let httpMock: HttpTestingController;
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        HttpClient, HttpHandler, HttpClientService
      ],
    })
    .compileComponents();
    service = TestBed.get(HttpClientService);
    httpMock = TestBed.get(HttpTestingController);
  }));


  beforeEach(() => {
    service = TestBed.inject(HttpClientService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('getCategories() should GET categories', () => {
    const categories = [
      {
        "categoryName": "Romantic",
        "hotelsInsideCategory": [
          {
            "id": 118,
            "name": "Cerri Hotel",
            "rate": 10,
            "price": 239,
            "city": "Sagaredzho",
            "description": "Hotel 'Cerri Hotel' at  Sagaredzho without parking place,  with restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160625_093158_UVRWFV.jpg",
            "stars": 1,
            "category": {
              "id": 1,
              "name": "Romantic",
              "categoryID": 1
            },
            "parking": false,
            "restaurant": true,
            "pets": false,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": true,
            "sauna": true,
            "fitness": true,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": true,
            "activity": "011",
            "otherFilters": "0100111111",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160625_093158_UVRWFV.jpg",
            "activityGym": false,
            "activityOpenBar": true,
            "activityRunning": true
          },
          {
            "id": 945,
            "name": "Zilwa Attitude",
            "rate": 10,
            "price": 519,
            "city": "Downtown Miami/City Center",
            "description": "Hotel 'Zilwa Attitude' at  Downtown Miami/City Center with parking place,  without restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160723_034820_1M4CUX.jpg",
            "stars": 5,
            "category": {
              "id": 1,
              "name": "Romantic",
              "categoryID": 1
            },
            "parking": true,
            "restaurant": false,
            "pets": false,
            "smoking": true,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": false,
            "fitness": false,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": false,
            "activity": "100",
            "otherFilters": "1001000100",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160723_034820_1M4CUX.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": false
          },
          {
            "id": 425,
            "name": "Baymont Inn & Suites Mt. Pleasant",
            "rate": 10,
            "price": 195,
            "city": "Ardeley",
            "description": "Hotel 'Baymont Inn & Suites Mt. Pleasant' at  Ardeley without parking place,  without restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160701_110400_G9U3GQ.jpg",
            "stars": 1,
            "category": {
              "id": 1,
              "name": "Romantic",
              "categoryID": 1
            },
            "parking": false,
            "restaurant": false,
            "pets": true,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": false,
            "fitness": true,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "110",
            "otherFilters": "0010110001",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160701_110400_G9U3GQ.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 680,
            "name": "Trip Hotel Ithaca",
            "rate": 10,
            "price": 770,
            "city": "Staatz",
            "description": "Hotel 'Trip Hotel Ithaca' at  Staatz with parking place,  without restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160710_025420_XPYKDQ.jpg",
            "stars": 1,
            "category": {
              "id": 1,
              "name": "Romantic",
              "categoryID": 1
            },
            "parking": true,
            "restaurant": false,
            "pets": true,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": false,
            "airConditioning": true,
            "freeWiFi": true,
            "sauna": true,
            "fitness": true,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "101",
            "otherFilters": "1010101111",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160710_025420_XPYKDQ.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": false
          },
          {
            "id": 163,
            "name": "Aparthotel Parque Tropical",
            "rate": 10,
            "price": 554,
            "city": "Calvario",
            "description": "Hotel 'Aparthotel Parque Tropical' at  Calvario with parking place,  without restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160625_205857_E2IKGL.jpg",
            "stars": 1,
            "category": {
              "id": 1,
              "name": "Romantic",
              "categoryID": 1
            },
            "parking": true,
            "restaurant": false,
            "pets": false,
            "smoking": true,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": true,
            "fitness": true,
            "activity_gym": false,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "001",
            "otherFilters": "1001000011",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160625_205857_E2IKGL.jpg",
            "activityGym": false,
            "activityOpenBar": true,
            "activityRunning": false
          }
        ]
      },
      {
        "categoryName": "Adventure",
        "hotelsInsideCategory": [
          {
            "id": 374,
            "name": "Spearfish Canyon Lodge",
            "rate": 10,
            "price": 452,
            "city": "Le Mesnil-Durand",
            "description": "Hotel 'Spearfish Canyon Lodge' at  Le Mesnil-Durand with parking place,  with restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160629_194320_MUZAIU.jpg",
            "stars": 5,
            "category": {
              "id": 2,
              "name": "Adventure",
              "categoryID": 2
            },
            "parking": true,
            "restaurant": true,
            "pets": true,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": true,
            "sauna": true,
            "fitness": false,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": true,
            "activity": "111",
            "otherFilters": "1110111110",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160629_194320_MUZAIU.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": true
          },
          {
            "id": 918,
            "name": "Quay West Suites Melbourne",
            "rate": 10,
            "price": 120,
            "city": "Adler",
            "description": "Hotel 'Quay West Suites Melbourne' at  Adler without parking place,  with restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160721_221053_PFVCSV.jpg",
            "stars": 5,
            "category": {
              "id": 2,
              "name": "Adventure",
              "categoryID": 2
            },
            "parking": false,
            "restaurant": true,
            "pets": true,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": false,
            "sauna": false,
            "fitness": false,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": true,
            "activity": "111",
            "otherFilters": "0111111000",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160721_221053_PFVCSV.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": true
          },
          {
            "id": 38,
            "name": "Boston Park Plaza",
            "rate": 10,
            "price": 487,
            "city": "Puerto del Rosario",
            "description": "Hotel 'Boston Park Plaza' at  Puerto del Rosario without parking place,  with restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160624_044156_1LE2OW.jpg",
            "stars": 1,
            "category": {
              "id": 2,
              "name": "Adventure",
              "categoryID": 2
            },
            "parking": false,
            "restaurant": true,
            "pets": false,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": true,
            "fitness": false,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "110",
            "otherFilters": "0101100010",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160624_044156_1LE2OW.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 224,
            "name": "Wingate By Wyndham Rome",
            "rate": 10,
            "price": 197,
            "city": "Estoril",
            "description": "Hotel 'Wingate By Wyndham Rome' at  Estoril with parking place,  with restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160626_131145_3RUZBA.jpg",
            "stars": 4,
            "category": {
              "id": 2,
              "name": "Adventure",
              "categoryID": 2
            },
            "parking": true,
            "restaurant": true,
            "pets": false,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": false,
            "sauna": true,
            "fitness": true,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "110",
            "otherFilters": "1100011011",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160626_131145_3RUZBA.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 441,
            "name": "azuLine Hotel Coral Beach",
            "rate": 10,
            "price": 785,
            "city": "Ahmedabad",
            "description": "Hotel 'azuLine Hotel Coral Beach' at  Ahmedabad without parking place,  with restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160701_234831_122N27.jpg",
            "stars": 1,
            "category": {
              "id": 2,
              "name": "Adventure",
              "categoryID": 2
            },
            "parking": false,
            "restaurant": true,
            "pets": false,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": true,
            "fitness": true,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": true,
            "activity": "111",
            "otherFilters": "0100000111",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160701_234831_122N27.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": true
          }
        ]
      },
      {
        "categoryName": "Holiday",
        "hotelsInsideCategory": [
          {
            "id": 711,
            "name": "La Quinta Inn & Suites Paso Robles",
            "rate": 10,
            "price": 252,
            "city": "Lake Lure",
            "description": "Hotel 'La Quinta Inn & Suites Paso Robles' at  Lake Lure with parking place,  with restaurant,  allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160711_005242_VH704W.jpg",
            "stars": 2,
            "category": {
              "id": 3,
              "name": "Holiday",
              "categoryID": 3
            },
            "parking": true,
            "restaurant": true,
            "pets": true,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": true,
            "fitness": false,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "010",
            "otherFilters": "1110010110",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160711_005242_VH704W.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 274,
            "name": "Days Inn Mason City",
            "rate": 10,
            "price": 447,
            "city": "Bacalar",
            "description": "Hotel 'Days Inn Mason City' at  Bacalar without parking place,  without restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160627_073515_7XXJN5.jpg",
            "stars": 4,
            "category": {
              "id": 3,
              "name": "Holiday",
              "categoryID": 3
            },
            "parking": false,
            "restaurant": false,
            "pets": false,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": false,
            "fitness": false,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "101",
            "otherFilters": "0000110100",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160627_073515_7XXJN5.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": false
          },
          {
            "id": 480,
            "name": "Best Western Hotel Bellevue au Lac",
            "rate": 10,
            "price": 695,
            "city": "Hallandale",
            "description": "Hotel 'Best Western Hotel Bellevue au Lac' at  Hallandale without parking place,  with restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160703_041427_B3ORL8.jpg",
            "stars": 3,
            "category": {
              "id": 3,
              "name": "Holiday",
              "categoryID": 3
            },
            "parking": false,
            "restaurant": true,
            "pets": true,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": false,
            "fitness": false,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": false,
            "activity": "100",
            "otherFilters": "0110110100",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160703_041427_B3ORL8.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": false
          },
          {
            "id": 439,
            "name": "Grand Hotel Miramare",
            "rate": 10,
            "price": 207,
            "city": "Kobe",
            "description": "Hotel 'Grand Hotel Miramare' at  Kobe without parking place,  with restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160701_230215_NOOYXB.jpg",
            "stars": 1,
            "category": {
              "id": 3,
              "name": "Holiday",
              "categoryID": 3
            },
            "parking": false,
            "restaurant": true,
            "pets": false,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": true,
            "fitness": true,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "110",
            "otherFilters": "0100110011",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160701_230215_NOOYXB.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 656,
            "name": "Cities Of Gold Casino",
            "rate": 10,
            "price": 389,
            "city": "Kyoto",
            "description": "Hotel 'Cities Of Gold Casino' at  Kyoto with parking place,  without restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160709_132458_42OMQY.jpg",
            "stars": 4,
            "category": {
              "id": 3,
              "name": "Holiday",
              "categoryID": 3
            },
            "parking": true,
            "restaurant": false,
            "pets": false,
            "smoking": true,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": true,
            "freeWiFi": true,
            "sauna": false,
            "fitness": true,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": true,
            "activity": "011",
            "otherFilters": "1001001101",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160709_132458_42OMQY.jpg",
            "activityGym": false,
            "activityOpenBar": true,
            "activityRunning": true
          }
        ]
      },
      {
        "categoryName": "Wellness",
        "hotelsInsideCategory": [
          {
            "id": 388,
            "name": "Hampton Inn Auburn",
            "rate": 10,
            "price": 170,
            "city": "Hay",
            "description": "Hotel 'Hampton Inn Auburn' at  Hay without parking place,  without restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160630_032512_0EJTG1.jpg",
            "stars": 5,
            "category": {
              "id": 4,
              "name": "Wellness",
              "categoryID": 4
            },
            "parking": false,
            "restaurant": false,
            "pets": true,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": false,
            "sauna": true,
            "fitness": false,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "010",
            "otherFilters": "0011111010",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160630_032512_0EJTG1.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 502,
            "name": "Welk Resort Branson Hotel",
            "rate": 10,
            "price": 888,
            "city": "Ostseebad Ahrenshoop",
            "description": "Hotel 'Welk Resort Branson Hotel' at  Ostseebad Ahrenshoop without parking place,  without restaurant,  allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160703_224159_977NUT.jpg",
            "stars": 5,
            "category": {
              "id": 4,
              "name": "Wellness",
              "categoryID": 4
            },
            "parking": false,
            "restaurant": false,
            "pets": true,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": false,
            "fitness": false,
            "activity_gym": false,
            "activity_running": false,
            "activity_openbar": false,
            "activity": "000",
            "otherFilters": "0010000000",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160703_224159_977NUT.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": false
          },
          {
            "id": 596,
            "name": "Mission Valley Resort",
            "rate": 10,
            "price": 617,
            "city": "Les Pennes-Mirabeau",
            "description": "Hotel 'Mission Valley Resort' at  Les Pennes-Mirabeau without parking place,  with restaurant,  allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160707_043527_SX9M1Q.jpg",
            "stars": 1,
            "category": {
              "id": 4,
              "name": "Wellness",
              "categoryID": 4
            },
            "parking": false,
            "restaurant": true,
            "pets": true,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": false,
            "fitness": false,
            "activity_gym": false,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "001",
            "otherFilters": "0110000000",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160707_043527_SX9M1Q.jpg",
            "activityGym": false,
            "activityOpenBar": true,
            "activityRunning": false
          },
          {
            "id": 417,
            "name": "Explorers Hotel at Disneyland Paris",
            "rate": 10,
            "price": 912,
            "city": "Panora",
            "description": "Hotel 'Explorers Hotel at Disneyland Paris' at  Panora with parking place,  with restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160701_035306_12065I.jpg",
            "stars": 4,
            "category": {
              "id": 4,
              "name": "Wellness",
              "categoryID": 4
            },
            "parking": true,
            "restaurant": true,
            "pets": true,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": true,
            "sauna": false,
            "fitness": false,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "010",
            "otherFilters": "1111111100",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160701_035306_12065I.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 50,
            "name": "Alpine Lodge Fairbanks",
            "rate": 10,
            "price": 653,
            "city": "Schonau",
            "description": "Hotel 'Alpine Lodge Fairbanks' at  Schonau with parking place,  with restaurant,  allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160624_135535_8MFP95.jpg",
            "stars": 2,
            "category": {
              "id": 4,
              "name": "Wellness",
              "categoryID": 4
            },
            "parking": true,
            "restaurant": true,
            "pets": true,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": false,
            "fitness": false,
            "activity_gym": false,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "001",
            "otherFilters": "1110000000",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160624_135535_8MFP95.jpg",
            "activityGym": false,
            "activityOpenBar": true,
            "activityRunning": false
          }
        ]
      },
      {
        "categoryName": "Family",
        "hotelsInsideCategory": [
          {
            "id": 761,
            "name": "Mercure Hotel Perth",
            "rate": 10,
            "price": 638,
            "city": "Manzanita",
            "description": "Hotel 'Mercure Hotel Perth' at  Manzanita without parking place,  without restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160713_125503_GHN0KM.jpg",
            "stars": 2,
            "category": {
              "id": 5,
              "name": "Family",
              "categoryID": 5
            },
            "parking": false,
            "restaurant": false,
            "pets": false,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": false,
            "airConditioning": true,
            "freeWiFi": true,
            "sauna": true,
            "fitness": true,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "010",
            "otherFilters": "0000001111",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160713_125503_GHN0KM.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 790,
            "name": "City Center Apartments",
            "rate": 10,
            "price": 741,
            "city": "Tukums",
            "description": "Hotel 'City Center Apartments' at  Tukums with parking place,  without restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160715_021426_S3EU9C.jpg",
            "stars": 2,
            "category": {
              "id": 5,
              "name": "Family",
              "categoryID": 5
            },
            "parking": true,
            "restaurant": false,
            "pets": false,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": true,
            "fitness": false,
            "activity_gym": false,
            "activity_running": false,
            "activity_openbar": false,
            "activity": "000",
            "otherFilters": "1000110010",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160715_021426_S3EU9C.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": false
          },
          {
            "id": 722,
            "name": "Days Inn Edmonton Airport",
            "rate": 10,
            "price": 379,
            "city": "Les Vivas",
            "description": "Hotel 'Days Inn Edmonton Airport' at  Les Vivas without parking place,  with restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160711_202116_UX7EEM.jpg",
            "stars": 5,
            "category": {
              "id": 5,
              "name": "Family",
              "categoryID": 5
            },
            "parking": false,
            "restaurant": true,
            "pets": false,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": true,
            "fitness": false,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "110",
            "otherFilters": "0101110110",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160711_202116_UX7EEM.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 718,
            "name": "Williamstown Motel",
            "rate": 10,
            "price": 853,
            "city": "Tbilisi",
            "description": "Hotel 'Williamstown Motel' at  Tbilisi with parking place,  without restaurant,  not allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160711_104925_86SBW5.jpg",
            "stars": 1,
            "category": {
              "id": 5,
              "name": "Family",
              "categoryID": 5
            },
            "parking": true,
            "restaurant": false,
            "pets": false,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": false,
            "fitness": true,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": true,
            "activity": "011",
            "otherFilters": "1000010101",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160711_104925_86SBW5.jpg",
            "activityGym": false,
            "activityOpenBar": true,
            "activityRunning": true
          },
          {
            "id": 201,
            "name": "Best Western Royal Beach Hotel",
            "rate": 10,
            "price": 673,
            "city": "Caminha",
            "description": "Hotel 'Best Western Royal Beach Hotel' at  Caminha without parking place,  without restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160626_034247_93ZKWV.jpg",
            "stars": 5,
            "category": {
              "id": 5,
              "name": "Family",
              "categoryID": 5
            },
            "parking": false,
            "restaurant": false,
            "pets": true,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": false,
            "fitness": true,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "101",
            "otherFilters": "0011110101",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160626_034247_93ZKWV.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": false
          }
        ]
      },
      {
        "categoryName": "Camping",
        "hotelsInsideCategory": [
          {
            "id": 278,
            "name": "Marina Tel Aviv Hotel",
            "rate": 10,
            "price": 436,
            "city": "Samara",
            "description": "Hotel 'Marina Tel Aviv Hotel' at  Samara without parking place,  without restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160627_094948_CRPHQT.jpg",
            "stars": 2,
            "category": {
              "id": 6,
              "name": "Camping",
              "categoryID": 6
            },
            "parking": false,
            "restaurant": false,
            "pets": true,
            "smoking": true,
            "swimmingPool": true,
            "beachFront": false,
            "airConditioning": true,
            "freeWiFi": false,
            "sauna": true,
            "fitness": true,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": false,
            "activity": "100",
            "otherFilters": "0011101011",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160627_094948_CRPHQT.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": false
          },
          {
            "id": 771,
            "name": "Best Western Plus Chateau Inn Sylvan Lake",
            "rate": 10,
            "price": 636,
            "city": "Winterberg",
            "description": "Hotel 'Best Western Plus Chateau Inn Sylvan Lake' at  Winterberg with parking place,  without restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160714_004114_SWUTZI.jpg",
            "stars": 5,
            "category": {
              "id": 6,
              "name": "Camping",
              "categoryID": 6
            },
            "parking": true,
            "restaurant": false,
            "pets": false,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": true,
            "freeWiFi": false,
            "sauna": true,
            "fitness": false,
            "activity_gym": true,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "110",
            "otherFilters": "1000111010",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160714_004114_SWUTZI.jpg",
            "activityGym": true,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 990,
            "name": "Red Roof Inn Tupelo",
            "rate": 10,
            "price": 662,
            "city": "Bang Rak Beach",
            "description": "Hotel 'Red Roof Inn Tupelo' at  Bang Rak Beach without parking place,  with restaurant,  not allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160725_221004_G4ZEFU.jpg",
            "stars": 1,
            "category": {
              "id": 6,
              "name": "Camping",
              "categoryID": 6
            },
            "parking": false,
            "restaurant": true,
            "pets": false,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": false,
            "airConditioning": false,
            "freeWiFi": true,
            "sauna": false,
            "fitness": true,
            "activity_gym": true,
            "activity_running": false,
            "activity_openbar": true,
            "activity": "101",
            "otherFilters": "0100100101",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160725_221004_G4ZEFU.jpg",
            "activityGym": true,
            "activityOpenBar": true,
            "activityRunning": false
          },
          {
            "id": 450,
            "name": "Best Western Plus Chocolate Lake Hotel",
            "rate": 10,
            "price": 929,
            "city": "Jincheng",
            "description": "Hotel 'Best Western Plus Chocolate Lake Hotel' at  Jincheng without parking place,  with restaurant,  allowing pets, with swimming pooland etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/8/20160702_030652_DVYD69.jpg",
            "stars": 5,
            "category": {
              "id": 6,
              "name": "Camping",
              "categoryID": 6
            },
            "parking": false,
            "restaurant": true,
            "pets": true,
            "smoking": false,
            "swimmingPool": true,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": true,
            "fitness": false,
            "activity_gym": false,
            "activity_running": true,
            "activity_openbar": false,
            "activity": "010",
            "otherFilters": "0110110010",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/8/20160702_030652_DVYD69.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": true
          },
          {
            "id": 184,
            "name": "Mendeli Street Hotel",
            "rate": 10,
            "price": 582,
            "city": "Deia",
            "description": "Hotel 'Mendeli Street Hotel' at  Deia without parking place,  without restaurant,  allowing pets, and etc. is waiting for you :)",
            "imagePath": "https://traffickcam.com/images/2017/7/20160626_003250_AH102N.jpg",
            "stars": 1,
            "category": {
              "id": 6,
              "name": "Camping",
              "categoryID": 6
            },
            "parking": false,
            "restaurant": false,
            "pets": true,
            "smoking": false,
            "swimmingPool": false,
            "beachFront": true,
            "airConditioning": false,
            "freeWiFi": false,
            "sauna": true,
            "fitness": false,
            "activity_gym": false,
            "activity_running": false,
            "activity_openbar": false,
            "activity": "000",
            "otherFilters": "0010010010",
            "rating_num": 5,
            "image": "https://traffickcam.com/images/2017/7/20160626_003250_AH102N.jpg",
            "activityGym": false,
            "activityOpenBar": false,
            "activityRunning": false
          }
        ]
      }
    ]
    service.getCategories().subscribe((cat) => {
      expect(cat).toEqual(categories);
    });
    const req = httpMock.expectOne('/getCategories');
    expect(req.request.method).toEqual("GET");
    req.flush(categories);

    httpMock.verify();
  });

  afterAll(() => TestBed.resetTestingModule());

});
